#=================================
#Database connection settings
#=================================

#MySQL database  URL
#todo_app=database names
spring.datasource.url=jdbc:mysql://localhost:3306/todoapp
#MySQL username
spring.datasource.username=root
#MySQL password
spring.datasource.password=root
#Auto create/update tables
spring.jpa.hibernate.ddl-auto=update
#shows SQL queries in console
spring.jpa.show-sql=true
#My SQL database support
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

